site_name: Melange

repo_url: https://github.com/melange-re/documentation-site/
edit_uri: blob/master/docs/

theme:
  name: readthedocs
  locale: en
  highlightjs: true
  hljs_languages:
    - ocaml

plugins:
  - search
  - print-site

nav:
  - Home: index.md
  - Why: rationale.md
  - Getting Started: getting-started.md
  - Learn:
    - New to OCaml?: new-to-ocaml.md
    - Package management: package-management.md
    - Build system: build-system.md
    - Communicate with JavaScript: communicate-with-javascript.md
    - Melange for X developers: melange-for-x-developers.md
  - Reference:
    - API: api.md
  - Try:
    - Playground: try.md
  - Talk:
    - Community: community.md

extra_css:
  - css/extra.css
