site_name: Melange

repo_url: https://github.com/melange-re/melange-re.github.io/
edit_uri: blob/master/docs/
site_url: https://melange.re

theme:
  name: readthedocs
  custom_dir: theme
  locale: en
  highlightjs: true
  hljs_languages:
    - ocaml

plugins:
  - search
  - print-site
  - mike

nav:
  - Home: index.md
  - Why: rationale.md
  - Getting Started: getting-started.md
  - Learn:
    - New to OCaml?: new-to-ocaml.md
    - Package management: package-management.md
    - Build system: build-system.md
    - Communicate with JavaScript: communicate-with-javascript.md
    - Melange for X developers: melange-for-x-developers.md
  - Melange for React Developers:
    - Introduction: melange-book/index.md
    - Installation: melange-book/installation.md
    - Counter: melange-book/counter.md
    - Melange Playground: melange-book/melange-playground.md
    - Celsius Converter, pt 1: melange-book/celsius-converter-1.md
  - Reference:
    - API: api.md
  - Try:
    - Playground: playground
  - About:
    - Community: community.md
    - Roadmap: roadmap.md

extra_css:
  - css/extra.css

extra_javascript:
  - js/toggleSyntaxButton.js
  - js/reasonml.js

markdown_extensions:
  - footnotes
